loomx.loom_version=1.18-SNAPSHOT
version=1.1.1-saps

plugin.deps.minecraft=26.2
plugin.deps.paper_api=26.2.build.129-stable

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.workers.max=4
org.gradle.tooling.parallel=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m

kotlin.code.style=official
ksp.incremental=false
