modLoader = "kotlinforforge"
loaderVersion = "${deps.kff.version}"
license = "${mod.license}"
issueTrackerURL = "${mod.links.issues}"

[[mods]]
modId = "${mod.id}"
version = "${mod.version}+${env.minecraft}-${env.loader}"
displayName = "${mod.name}"
updateJSONURL = "${mod.links.forge_updates}"
displayURL = "${mod.links.homepage}"
logoFile = "assets/${mod.id}/icon.png"
authors = "${mod.author}"
description = '''${mod.description}'''

[[mixins]]
config = "${mod.id}.mixins.json"

[[dependencies.${ mod.id }]]
modId = "forge"
mandatory = true
versionRange = "${deps.forge.range | versionRange}"

[[dependencies.${ mod.id }]]
modId = "kotlinforforge"
mandatory = true
versionRange = "${deps.kff.range | versionRange}"

[[dependencies.${ mod.id }]]
modId = "xaeroworldmap"
mandatory = true
versionRange = "${deps.xaero_world_map.range | versionRange}"

[[dependencies.${ mod.id }]]
modId = "xaerominimap"
mandatory = true
versionRange = "${deps.xaero_minimap.range | versionRange}"

[[dependencies.${ mod.id }]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "${deps.yacl.range | versionRange}"

