modLoader="kotlinforforge"
loaderVersion="${deps.kff.version}"
license="${mod.license}"
issueTrackerURL="${mod.links.issues}"

[[mods]]
modId="${mod.id}"
version="${mod.version}+${env.minecraft}-${env.loader}"
displayName="${mod.name}"
updateJSONURL="${mod.links.neoforge_updates}"
displayURL="${mod.links.homepage}"
logoFile="assets/${mod.id}/icon.png"
authors="${mod.author}"
description='''${mod.description}'''

[[mixins]]
config="${mod.id}.mixins.json"

[[dependencies.${mod.id}]]
modId="neoforge"
type="required"
versionRange="${deps.neoforge.range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod.id}]]
modId="minecraft"
type="required"
versionRange="${deps.minecraft.range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod.id}]]
modId = "kotlinforforge"
type = "required"
versionRange = "${deps.kff.range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod.id}]]
modId="xaeroworldmap"
type="required"
versionRange="${deps.xaero_world_map.range}"

[[dependencies.${mod.id}]]
modId="xaerominimap"
type="required"
versionRange="${deps.xaero_minimap.range}"

[[dependencies.${mod.id}]]
modId="yet_another_config_lib_v3"
type="required"
versionRange="${deps.yacl.range}"

